version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run: git submodule update --recursive --init deps/spiffing deps/rapidxml deps/sigslot
     - run: docker build -t surevinecom/metre:$CIRCLE_BRANCH .
